// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/genres/getGenres': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/genres/getGenres').default>>>>
    }
    '/api/player/getPlayerState': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/getPlayerState').default>>>>
    }
    '/api/playlists/addToPlaylist': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/addToPlaylist').default>>>>
    }
    '/api/playlists/generatePlaylist': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/generatePlaylist').default>>>>
    }
    '/api/playlists/getPlaylist': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/getPlaylist').default>>>>
    }
    '/api/playlists/getPlaylistItems': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/getPlaylistItems').default>>>>
    }
    '/api/playlists/getPlaylists': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/getPlaylists').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}